services:

  scrapers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LMSTUDIO_URL=http://host.docker.internal:1234/v1
      - MONGO_URI=${MONGO_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - SCRAPERS_URL=http://scrapers:5000
    depends_on:
      - scrapers
    networks:
      - app

networks:
  app:
    driver: bridge
